-- MySQL Script generated by MySQL Workbench
-- Thu Sep 28 11:41:41 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project` ;

CREATE TABLE IF NOT EXISTS `project` (
  `id` VARCHAR(24) NOT NULL,
  `name` VARCHAR(255) NULL,
  `description` VARCHAR(100) NULL,
  `creater` VARCHAR(24) NULL COMMENT 'project创建者',
  `creater_name` VARCHAR(45) NULL,
  `zone_id` VARCHAR(24) NULL,
  `pkg_expire` INT NULL,
  `pkg_expire_after_download` INT NULL,
  `allow_pkg_level_expiration` TINYINT NULL,
  `max_seg_num` BIGINT NULL,
  `min_seg_size` BIGINT NULL,
  `max_seg_size` BIGINT NULL,
  `max_upload_bandwidth` BIGINT NULL,
  `max_download_bandwidth` BIGINT NULL,
  `save_mode` INT NULL COMMENT '保存模式，0:分片保存 1:完整文件',
  `create_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  `pic_url` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_project_1` (`create_at` ASC),
  INDEX `idx_project_2` (`creater` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_user` ;

CREATE TABLE IF NOT EXISTS `project_user` (
  `user_id` VARCHAR(24) NOT NULL,
  `project_id` VARCHAR(24) NOT NULL,
  `role_id` TINYINT NOT NULL,
  `settings_id` VARCHAR(24) NULL,
  `create_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  `id` VARCHAR(24) NOT NULL,
  UNIQUE INDEX `idx_project_user_1` (`project_id` ASC, `user_id` ASC),
  UNIQUE INDEX `idx_project_user_2` (`user_id` ASC, `project_id` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `package`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `package` ;

CREATE TABLE IF NOT EXISTS `package` (
  `id` VARCHAR(24) NOT NULL,
  `project_id` VARCHAR(24) NULL,
  `title` VARCHAR(45) NULL,
  -- `size` BIGINT(11) NULL,
  `notes` VARCHAR(255) NULL,
  `num_files` INT NULL,
  `size` BIGINT NULL,
  `origin_size` BIGINT NULL,
  `expires` BIGINT NULL,
  `expires_after_download` BIGINT NULL,
  `is_closed` TINYINT NULL,
  `is_broken` TINYINT NULL,
  `is_downloadable` TINYINT NULL,
  `downloadable_at` DATETIME NULL,
  `is_deleted` TINYINT NULL,
  `deleted_by` VARCHAR(255) NULL,
  `deleted_at` DATETIME NULL,
  `create_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `file` ;

CREATE TABLE IF NOT EXISTS `file` (
  `id` VARCHAR(24) NOT NULL,
  `name` VARCHAR(255) NULL,
  `package_id` VARCHAR(24) NULL,
  `size` BIGINT(11) NULL,
  `project_id` VARCHAR(24) NULL,
  `path` TEXT NULL,
  `type` INT NULL,
  `mode` INT NULL,
  `path_abs` TEXT NULL,
  `composition` INT NULL,
  `origin_size` BIGINT NULL,
  `num_segs` INT NULL,
  `seg_avg_size` BIGINT NULL,
  `storage` VARCHAR(255) NULL,
  `storage_mode` INT NULL,
  `encryption_type` INT NULL,
  `encryption_block_size` INT NULL,
  `digest_method` VARCHAR(32) NULL,
  `digest` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `package_job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `package_job` ;

CREATE TABLE IF NOT EXISTS `package_job` (
  `id` VARCHAR(24) NOT NULL,
  `user_id` VARCHAR(24) NULL,
  `package_id` VARCHAR(24) NULL,
  `operation` INT NULL COMMENT '1:上传  2：下载',
  `state` INT NULL COMMENT '0：空闲 1：正在传输 2：完成 3：中断 100:上传下载都完成',
  `is_read` TINYINT NULL,
  `start_at` DATETIME NULL,
  `finish_at` DATETIME NULL,
  `finished_times` INT NULL,
  `finish_all_at` DATETIME NULL,
  `is_deleted` TINYINT NULL,
  `deleted_at` DATETIME NULL,
  `is_disable` TINYINT NULL,
  `disable_at` DATETIME NULL,
  `create_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `package_id_UNIQUE` (`package_id` ASC),
  UNIQUE INDEX `operation_UNIQUE` (`operation` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `file_job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `file_job` ;

CREATE TABLE IF NOT EXISTS `file_job` (
  `id` VARCHAR(24) NOT NULL,
  `user_id` VARCHAR(24) NOT NULL,
  `file_id` VARCHAR(24) NOT NULL,
  `operation` INT NOT NULL COMMENT '1:上传 2：下载',
  `package_id` VARCHAR(24) NULL,
  `state` INT NULL COMMENT '0：空闲 1：正在传输 2：完成 3：中断',
  `finished_size` BIGINT NULL,
  `start_at` DATETIME NULL,
  `finish_at` DATETIME NULL,
  `segs_state_bitmap` VARCHAR(255) NULL,
  `checked` INT NULL,
  `finished_times` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `task` ;

CREATE TABLE IF NOT EXISTS `task` (
  `id` VARCHAR(24) NOT NULL,
  `user_id` VARCHAR(24) NULL,
  `package_id` VARCHAR(24) NULL,
  `file_id` VARCHAR(24) NULL,
  `project_id` VARCHAR(24) NULL,
  `zone_id` VARCHAR(24) NULL,
  `operation` INT NULL,
  `state` INT NULL,
  `allocated_bitrate` BIGINT(11) NULL,
  `max_bitrate` BIGINT(11) NULL,
  `min_bitrate` BIGINT(11) NULL,
  `peer_ip` VARCHAR(64) NULL,
  `create_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  `start_at` DATETIME NULL,
  `total_traffic` BIGINT NULL,
  `total_bytes` BIGINT NULL,
  `finish_at` DATETIME NULL,
  `avg_bitrate` BIGINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `log_op`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `log_op` ;

CREATE TABLE IF NOT EXISTS `log_op` (
  `id` VARCHAR(24) NOT NULL,
  `operator_id` VARCHAR(24) NULL COMMENT '操作者id',
  `operator_name` VARCHAR(45) NULL COMMENT '操作者名称',
  `to_user_id` VARCHAR(24) NULL COMMENT '被操作者',
  `to_user_name` VARCHAR(45) NULL,
  `action` INT NULL COMMENT '// 1:登录 2：登出 3：创建包裹 4：删除包裹 5：上传 6：下载 7：创建project 8：删除project 9：激活mini app 10:修改project 11:修改project成员 12：修改project的成员权限 13：修改setting 14:修改默认接收者 15：离开project 16:创建group 17：修改分组 18：修改分组成员 19：删除分组 20：邀请用户 21：激活用户 22:管理员踢出用户\n-1:其他',
  `details` VARCHAR(500) NULL,
  `project_id` VARCHAR(24) NULL,
  `project_name` VARCHAR(45) NULL,
  `operation_at` DATETIME NULL,
  `ip` VARCHAR(45) NULL,
  `data` VARCHAR(2000) NULL COMMENT '{\"file_id\":cxxx,\"package_id\":ddd}',
  PRIMARY KEY (`id`),
  INDEX `idx_log_op_1` (`operation_at` ASC, `action` ASC, `operator_id` ASC),
  INDEX `idx_log_op_2` (`operation_at` ASC, `operator_id` ASC, `action` ASC),
  INDEX `idx_log_op_3` (`operation_at` ASC, `project_id` ASC))
ENGINE = InnoDB
COMMENT = '登录、登出、创建包裹、上传、等操作日志，\n因为action不同，有些字段可能没有值\n只要用户有动作就记录日志';


-- -----------------------------------------------------
-- Table `log_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `log_task` ;

CREATE TABLE IF NOT EXISTS `log_task` (
  `id` VARCHAR(24) NOT NULL,
  `user_id` VARCHAR(24) NULL,
  `user_name` VARCHAR(45) NULL,
  `package_id` VARCHAR(24) NULL,
  `package_name` VARCHAR(45) NULL,
  `file_id` VARCHAR(24) NULL,
  `file_name` VARCHAR(50) NULL,
  `project_id` VARCHAR(24) NULL,
  `project_name` VARCHAR(50) NULL,
  `zone_id` VARCHAR(24) NULL,
  `allocated_bitrate` BIGINT NULL,
  `operation` INT NULL COMMENT '1:上传 2：下载',
  `state` INT NULL COMMENT '0：没有发生传输 2：成功结束 3：中断（发生过传输）',
  `average_bitrate` BIGINT NULL,
  `peer_ip` VARCHAR(64) NULL,
  `create_at` DATETIME NULL,
  `start_at` DATETIME NULL,
  `finish_at` DATETIME NULL,
  `size` BIGINT NULL,
  `root_user_id` VARCHAR(24) NULL,
  `root_user_name` VARCHAR(50) NULL,
  `traffic` BIGINT NULL,
  `task_id` VARCHAR(24) NULL,
  `task_create_at` DATETIME NULL COMMENT 'task创建时间',
  PRIMARY KEY (`id`),
  INDEX `idx_log_task_1` (`finish_at` ASC, `root_user_id` ASC),
  INDEX `idx_log_task_2` (`root_user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `log_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `log_file` ;

CREATE TABLE IF NOT EXISTS `log_file` (
  `id` VARCHAR(24) NOT NULL,
  `user_id` VARCHAR(24) NULL,
  `user_name` VARCHAR(45) NULL,
  `package_id` VARCHAR(24) NULL,
  `package_name` VARCHAR(45) NULL,
  `file_id` VARCHAR(24) NULL,
  `file_name` VARCHAR(50) NULL,
  `project_id` VARCHAR(24) NULL,
  `project_name` VARCHAR(50) NULL,
  `operation` INT NULL COMMENT '1：上传成功 2：下载成功 4：删除成功',
  `state` INT NULL COMMENT '0:空闲 1：正在传输 2：成功 ',
  `operation_at` DATETIME NULL,
  `size` BIGINT NULL COMMENT '压缩后的size',
  `root_user_id` VARCHAR(24) NULL,
  `root_user_name` VARCHAR(50) NULL,
  `finish_size` BIGINT NULL COMMENT '实际完成的size',
  PRIMARY KEY (`id`),
  INDEX `idx_log_file` (`operation_at` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `log_package`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `log_package` ;

CREATE TABLE IF NOT EXISTS `log_package` (
  `id` VARCHAR(24) NOT NULL,
  `user_id` VARCHAR(24) NULL,
  `user_name` VARCHAR(45) NULL,
  `package_id` VARCHAR(24) NULL,
  `package_name` VARCHAR(45) NULL,
  `project_id` VARCHAR(24) NULL,
  `project_name` VARCHAR(50) NULL,
  `operation` INT NULL COMMENT '1：上传成功 2：下载成功',
  `state` INT NULL,
  `operation_at` DATETIME NULL,
  `size` BIGINT NULL COMMENT '压缩后的size',
  `user_id_upload` VARCHAR(24) NULL,
  `user_name_upload` VARCHAR(50) NULL,
  `root_user_id` VARCHAR(24) NULL,
  `root_user_name` VARCHAR(50) NULL,
  `file_cnt` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_log_package_1` (`operation_at` ASC))
ENGINE = InnoDB
COMMENT = '操作成功时候才记录该日志';


-- -----------------------------------------------------
-- Table `log_task_hour`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `log_task_hour` ;

CREATE TABLE IF NOT EXISTS `log_task_hour` (
  `id` VARCHAR(24) NOT NULL,
  `user_id` VARCHAR(24) NULL,
  `user_name` VARCHAR(45) NULL,
  `package_id` VARCHAR(24) NULL,
  `package_name` VARCHAR(45) NULL,
  `file_id` VARCHAR(24) NULL,
  `file_name` VARCHAR(50) NULL,
  `project_id` VARCHAR(24) NULL,
  `project_name` VARCHAR(50) NULL,
  `zone_id` VARCHAR(24) NULL,
  `operation` INT NULL COMMENT '1:上传 2：下载',
  `allocated_bitrate` BIGINT(11) NULL,
  `max_bitrate` BIGINT(11) NULL,
  `min_bitrate` BIGINT NULL,
  `average_bitrate` BIGINT NULL,
  `peer_ip` VARCHAR(64) NULL,
  `traffic` BIGINT(11) NULL,
  `start_at` DATETIME NULL,
  `finish_at` DATETIME NULL,
  `period` INT NULL,
  `size` BIGINT NULL,
  `root_user_id` VARCHAR(24) NULL,
  `root_user_name` VARCHAR(50) NULL,
  `minute_bitrate` VARCHAR(1000) NULL COMMENT '上传或下载期间，每分钟的平均码率。是一个数组json，每个位置表示1分钟平均码率。单位：k\neg. [343,545,66,11,4]',
  `task_id` VARCHAR(24) NULL,
  `create_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_log_task_hour_1` (`finish_at` ASC, `task_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `user_id` VARCHAR(24) NOT NULL,
  `user_name` VARCHAR(50) NULL,
  `language` VARCHAR(10) NOT NULL,
  `time_zone` TINYINT NOT NULL,
  `email` VARCHAR(50) NULL,
  `mobile_phone` VARCHAR(45) NULL,
  `company` VARCHAR(100) NULL,
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `product_code` VARCHAR(3) NULL COMMENT '1:从cydex注册 2：其他地方注册的用户',
  `pic_url` VARCHAR(100) NULL DEFAULT '',
  PRIMARY KEY (`user_id`),
  INDEX `idx_user_1` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_role_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_role_permission` ;

CREATE TABLE IF NOT EXISTS `project_role_permission` (
  `id` VARCHAR(24) NOT NULL,
  `code` VARCHAR(6) NOT NULL,
  `role_id` TINYINT NOT NULL,
  `value1` INT NULL,
  `value2` INT NULL,
  `is_allowed` TINYINT NULL,
  `create_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  `description` VARCHAR(60) NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_project_role_detail_1` (`role_id` ASC),
  UNIQUE INDEX `idx_project_role_detail_2` (`role_id` ASC, `code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `language_pkg`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `language_pkg` ;

CREATE TABLE IF NOT EXISTS `language_pkg` (
  `lan_code` VARCHAR(10) NULL COMMENT 'zh:简体中文 zh-tw:繁体中文 en：英语',
  `key` VARCHAR(30) NULL,
  `value` VARCHAR(50) NULL,
  UNIQUE INDEX `idx_language_pkg_1` (`key` ASC, `lan_code` ASC))
ENGINE = InnoDB
COMMENT = '语言包，为了多国语言版';


-- -----------------------------------------------------
-- Table `project_setting_pkg_events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_setting_pkg_events` ;

CREATE TABLE IF NOT EXISTS `project_setting_pkg_events` (
  `id` VARCHAR(24) NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  `name` VARCHAR(45) NULL,
  `settings_id` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_project_setting_pkg_events_1` (`settings_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_setting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_setting` ;

CREATE TABLE IF NOT EXISTS `project_setting` (
  `id` VARCHAR(24) NOT NULL COMMENT '0:project 创建者 1：管理员 2：普通用户',
  `create_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  `operation` TINYINT NULL DEFAULT 2 COMMENT '1.仅上传 2.仅下载 3.Both',
  `upload_max_bps` BIGINT NULL DEFAULT 0,
  `download_max_bps` BIGINT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_default_recipients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_default_recipients` ;

CREATE TABLE IF NOT EXISTS `project_default_recipients` (
  `user_id` VARCHAR(24) NOT NULL COMMENT '0:project 创建者 1：管理员 2：普通用户',
  `project_id` VARCHAR(24) NOT NULL,
  `create_at` DATETIME NULL,
  `recipient_id` VARCHAR(24) NOT NULL,
  UNIQUE INDEX `idx_project_default_recipient_1` (`user_id` ASC, `project_id` ASC, `recipient_id` ASC),
  INDEX `idx_project_default_recipient_2` (`project_id` ASC, `user_id` ASC),
  INDEX `idx_project_default_recipient_3` (`recipient_id` ASC, `project_id` ASC, `user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_group` ;

CREATE TABLE IF NOT EXISTS `project_group` (
  `id` VARCHAR(24) NOT NULL,
  `group_name` VARCHAR(50) NULL,
  `project_id` VARCHAR(24) NOT NULL COMMENT 'zh:简体中文 zh-tw:繁体中文 en：英语',
  `create_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  `user_id` VARCHAR(24) NULL COMMENT '创建者id',
  INDEX `idx_project_group_1` (`project_id` ASC, `user_id` ASC),
  PRIMARY KEY (`id`),
  INDEX `idx_project_group_2` (`user_id` ASC, `project_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_group_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_group_member` ;

CREATE TABLE IF NOT EXISTS `project_group_member` (
  `user_id` VARCHAR(24) NOT NULL,
  `group_id` VARCHAR(24) NULL,
  `create_at` DATETIME NULL,
  `update_at` DATETIME NULL,
  `id` VARCHAR(24) NOT NULL,
  INDEX `idx_project_group_member_1` (`group_id` ASC, `user_id` ASC),
  INDEX `idx_project_group_member_2` (`user_id` ASC, `group_id` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_setting_pub_methods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project_setting_pub_methods` ;

CREATE TABLE IF NOT EXISTS `project_setting_pub_methods` (
  `id` VARCHAR(24) NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  `name` VARCHAR(45) NULL,
  `settings_id` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_project_setting_pub_methods_1` (`settings_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zone` ;

CREATE TABLE IF NOT EXISTS `zone` (
  `id` VARCHAR(24) NOT NULL,
  `name` VARCHAR(50) NULL,
  `host` VARCHAR(50) NOT NULL,
  `description` VARCHAR(100) NULL,
  `secret_key` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_zone_1` (`host` ASC),
  INDEX `idx_zone_2` (`secret_key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_login` ;

CREATE TABLE IF NOT EXISTS `user_login` (
  `user_id` VARCHAR(24) NOT NULL,
  `user_name` VARCHAR(50) NULL,
  `language` VARCHAR(10) NULL,
  `time_zone` TINYINT NULL,
  `email` VARCHAR(50) NULL,
  `os_type` VARCHAR(20) NULL,
  `os_detail` VARCHAR(100) NULL,
  `last_login` DATETIME NULL COMMENT '上次登陆时间',
  `state` TINYINT NULL COMMENT 'mini app状态 1：在线 0：离线',
  PRIMARY KEY (`user_id`),
  INDEX `idx_user_1` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `server_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `server_config` ;

CREATE TABLE IF NOT EXISTS `server_config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `version` VARCHAR(45) NOT NULL COMMENT '服务端当前版本号 比如：1.0.0',
  `compatibility_s` INT NOT NULL COMMENT '兼容指start',
  `compatibility_e` INT NOT NULL COMMENT '兼容值end',
  `max_available_traffic` BIGINT NULL COMMENT '免费用户的最大可用流量，单位：兆',
  `cydex_manager_code` VARCHAR(24) NULL COMMENT '管理中心识别号，用于区分各地管理中心',
  `max_upload_bps` BIGINT NULL COMMENT '默认的每个人的最大上传带宽，单位 bit/s',
  `max_download_bps` BIGINT NULL COMMENT '默认的每个人的最大下载带宽，单位 bit/s',
  `project_max_segs_num` INT NULL COMMENT '最多分片个数',
  `project_min_seg_size` BIGINT NULL COMMENT '最小分片字节',
  `project_max_seg_size` BIGINT NULL COMMENT '最大分片字节',
  `calcu_traffic_interval` INT NULL COMMENT '实时计算用户流量余额的时间间隔，单位：分钟',
  `package_expire` INT NULL COMMENT '包裹过期时间，单位：秒',
  `package_delete_expire` INT NULL COMMENT '包裹被删除后多久包裹记录被删除，单位：天，默认15天',
  `system_start_dt` DATETIME NULL COMMENT '系统正式运营时间。所有结算，报表的初始时间都根据这个值为准。小于这个时间的数据都不作为正式数据。',
  `overdraw_n` DECIMAL(5,2) NULL COMMENT '可透支流量系数\n可透支流量=（注册时长*0.2+购买流量总量*0.8）*n',
  `size_n` VARCHAR(45) NULL COMMENT '可用存储空间系数\n可用存储空间 = 剩余流量*n',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yw_black_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yw_black_list` ;

CREATE TABLE IF NOT EXISTS `yw_black_list` (
  `id` VARCHAR(24) NOT NULL,
  `user_id` VARCHAR(24) NOT NULL COMMENT '用户id',
  `operate_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `operate_id` VARCHAR(24) NULL COMMENT '操作者id(指运维操作者id，不是用户id)',
  PRIMARY KEY (`id`),
  INDEX `idx_yw_black_list_1` (`user_id` ASC),
  INDEX `idx_yw_black_list_2` (`operate_id` ASC))
ENGINE = InnoDB
COMMENT = 'yw开头的表是指给运维用的\n';


-- -----------------------------------------------------
-- Table `yw_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yw_user` ;

CREATE TABLE IF NOT EXISTS `yw_user` (
  `user_id` VARCHAR(24) NOT NULL,
  `user_name` VARCHAR(50) NULL,
  `password` VARCHAR(45) NOT NULL,
  `create_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  INDEX `idx_yw_user_1` (`user_id` ASC))
ENGINE = InnoDB
COMMENT = '运维人员表';


-- -----------------------------------------------------
-- Table `yw_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yw_role` ;

CREATE TABLE IF NOT EXISTS `yw_role` (
  `role_id` INT NOT NULL COMMENT '9:admin\n1:user',
  `role_name` VARCHAR(45) NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
COMMENT = '运维角色\n';


-- -----------------------------------------------------
-- Table `yw_role_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yw_role_user` ;

CREATE TABLE IF NOT EXISTS `yw_role_user` (
  `role_id` INT NOT NULL COMMENT '9:admin\n1:normal',
  `user_id` VARCHAR(24) NOT NULL,
  UNIQUE INDEX `idx_yw_role_user_1` (`role_id` ASC, `user_id` ASC))
ENGINE = InnoDB
COMMENT = '运维角色\n';


-- -----------------------------------------------------
-- Table `yw_log_op`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yw_log_op` ;

CREATE TABLE IF NOT EXISTS `yw_log_op` (
  `id` VARCHAR(24) NOT NULL,
  `operator_id` VARCHAR(24) NULL COMMENT '操作者id',
  `operator_name` VARCHAR(45) NULL COMMENT '操作者名称',
  `action` INT NULL COMMENT '// 1:修改黑名单列表 2：踢出用户',
  `details` VARCHAR(500) NULL,
  `operation_at` DATETIME NULL,
  `data` VARCHAR(500) NULL COMMENT '{\"file_id\":cxxx,\"package_id\":ddd}',
  PRIMARY KEY (`id`),
  INDEX `idx_yw_log_op_1` (`operation_at` ASC, `action` ASC, `operator_id` ASC),
  INDEX `idx_yw_log_op_2` (`operation_at` ASC, `operator_id` ASC, `action` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `js_user_quota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `js_user_quota` ;

CREATE TABLE IF NOT EXISTS `js_user_quota` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(24) NOT NULL,
  `available_traffic` BIGINT NULL COMMENT '当前可用流量',
  `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `calculate_dt` DATETIME NULL,
  `debt_traffic` BIGINT NULL COMMENT '欠费流量',
  `use_size` BIGINT NULL COMMENT '当前占用的磁盘空间，单位：byte',
  PRIMARY KEY (`id`),
  INDEX `idx_js_user_quota_1` (`user_id` ASC))
ENGINE = InnoDB
COMMENT = '用户流量余额表';


-- -----------------------------------------------------
-- Table `js_user_quota_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `js_user_quota_status` ;

CREATE TABLE IF NOT EXISTS `js_user_quota_status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `calculate_dt` DATETIME NOT NULL COMMENT '用户剩余流量计算时间',
  `calculate_status` VARCHAR(20) NULL COMMENT '结算状态 OK:结算成功\n',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '记录刷新流量余额时间点';


-- -----------------------------------------------------
-- Table `js_user_quota_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `js_user_quota_detail` ;

CREATE TABLE IF NOT EXISTS `js_user_quota_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ticket_id` VARCHAR(45) NULL COMMENT '票据id，即产生该可用流量的相关联的业务id',
  `traffic` BIGINT NULL COMMENT '可用流量，单位 byte',
  `start_at` DATETIME NULL COMMENT '有效期开始时间',
  `end_at` DATETIME NULL,
  `type` INT NULL COMMENT '类型 100：免费 200：优惠券 300：套餐  400：流量包',
  `user_id` VARCHAR(24) NULL,
  `insert_id` VARCHAR(45) NULL COMMENT 'js_user_quota_insert表的id，表示该条detail记录的来源',
  PRIMARY KEY (`id`),
  INDEX `idx_js_user_quota_detail_1` (`user_id` ASC, `end_at` ASC))
ENGINE = InnoDB
COMMENT = '用户流量余额明细表';


-- -----------------------------------------------------
-- Table `js_user_quota_add`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `js_user_quota_add` ;

CREATE TABLE IF NOT EXISTS `js_user_quota_add` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dt` DATETIME NULL COMMENT '结算时间 ',
  `user_id` VARCHAR(24) NULL,
  `data` VARCHAR(2000) NULL COMMENT '结算后数据。json格式，eg：[{ticket_id:\"111\",traffic:100,start_at:\"2018-01-01 12:00:00\",end_at:\"2018-01-01 12:00:00\",type:1,user_id:\"001\"},{} ...]',
  `available_traffic` BIGINT NULL COMMENT '结算后可用流量',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '流量余额结算日志表';


-- -----------------------------------------------------
-- Table `js_user_quota_insert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `js_user_quota_insert` ;

CREATE TABLE IF NOT EXISTS `js_user_quota_insert` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ticket_id` VARCHAR(45) NULL COMMENT '票据id，即产生该可用流量的相关联的业务id',
  `traffic` BIGINT NULL COMMENT '可用流量，单位 byte',
  `start_at` DATETIME NULL COMMENT '有效期开始时间',
  `end_at` DATETIME NULL,
  `type` INT NOT NULL COMMENT '类型 100：免费 200：优惠券 300：套餐  400：流量包',
  `user_id` VARCHAR(24) NULL,
  `dt` DATETIME NULL COMMENT '插入时间',
  `activate` TINYINT NULL COMMENT '是否已生效 1：已生效 0：未生效\n每个流量包只能生效一次',
  PRIMARY KEY (`id`),
  INDEX `idx_js_user_quota_insert_1` (`user_id` ASC, `dt` ASC),
  INDEX `idx_js_user_quota_insert_2` (`start_at` ASC, `user_id` ASC),
  INDEX `idx_js_user_quota_insert_3` (`ticket_id` ASC))
ENGINE = InnoDB
COMMENT = '用户流量生效表。\n该表存放所有开始生效的流量\n比如：如果买了一个套餐开始生效，则会在该表以及js_user_quota_detail表中各插入一条记录。\n这个表用于万一结算有问题时进行回滚重复结算。';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;