-- MySQL Script generated by MySQL Workbench
-- Wed Aug 16 10:39:27 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `us_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `us_user` ;

CREATE TABLE IF NOT EXISTS `us_user` (
  `user_id` VARCHAR(24) NOT NULL,
  `user_name` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `create_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `mobile_phone` VARCHAR(45) NULL,
  `company` VARCHAR(100) NULL,
  `product_code` VARCHAR(3) NULL COMMENT '产品code，表明从哪个产品注册的\n001:cydex 002:官网 003:caton.net',
  `pic_url` VARCHAR(100) NULL DEFAULT '',
   `is_complete` TINYINT(4),
  PRIMARY KEY (`user_id`),
  INDEX `idx_user_1` (`email` ASC),
  INDEX `idx_user_2` (`user_name` ASC),
  INDEX `idx_user_3` (`create_at` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `us_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `us_product` ;

CREATE TABLE IF NOT EXISTS `us_product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_code` VARCHAR(3) NOT NULL,
  `product_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_us_product_1` (`product_code` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;